/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bioskop;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;



/**
 *
 * @author Agiel Asy'ari
 */
public class Main extends javax.swing.JFrame {

    private String Film;
    private int Studio;

	/**
	 * Creates new form Main
	 */
public Main() {
    initComponents();
	}

/**
 * This method is called from within the constructor to initialise the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTop = new javax.swing.JLabel();
        jlblTop2 = new javax.swing.JLabel();
        jplTktTp = new javax.swing.JPanel();
        jlblTktTp = new javax.swing.JLabel();
        jlblNoTkt = new javax.swing.JLabel();
        jlblDay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbSweet = new javax.swing.JComboBox<>();
        jcbVel = new javax.swing.JComboBox<>();
        jcbGold = new javax.swing.JComboBox<>();
        jcbReg = new javax.swing.JComboBox<>();
        jcbDay = new javax.swing.JComboBox<>();
        jlblTktTp1 = new javax.swing.JLabel();
        jcbFilm = new javax.swing.JComboBox<>();
        jlblTktTp2 = new javax.swing.JLabel();
        jcbStudio = new javax.swing.JComboBox<>();
        jbtnAdd = new javax.swing.JButton();
        jbtnRst = new javax.swing.JButton();
        jplTktTp1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jlblTime = new javax.swing.JLabel();
        jlblNoT = new javax.swing.JLabel();
        jlblON = new javax.swing.JLabel();
        jlblDis = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblOrdDet = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlblFilm = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblStudio = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();
        jlblPrices = new javax.swing.JLabel();
        jlblPrices1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jlblTop.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jlblTop.setForeground(new java.awt.Color(153, 153, 153));
        jlblTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTop.setText("Cinema XXI Surabaya");

        jlblTop2.setFont(new java.awt.Font("Lucida Blackletter", 0, 24)); // NOI18N
        jlblTop2.setForeground(new java.awt.Color(153, 153, 153));
        jlblTop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlblTop, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblTop2)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTop)
                    .addComponent(jlblTop2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jplTktTp.setBackground(new java.awt.Color(51, 51, 51));
        jplTktTp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jplTktTp.setForeground(new java.awt.Color(51, 51, 51));
        jplTktTp.setPreferredSize(new java.awt.Dimension(430, 222));

        jlblTktTp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblTktTp.setForeground(new java.awt.Color(153, 153, 153));
        jlblTktTp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTktTp.setText("Tipe Tiket");
        jlblTktTp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblNoTkt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblNoTkt.setForeground(new java.awt.Color(153, 153, 153));
        jlblNoTkt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNoTkt.setText("JumlahTickets ");
        jlblNoTkt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblDay.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblDay.setForeground(new java.awt.Color(153, 153, 153));
        jlblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDay.setText("Hari");
        jlblDay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sweet");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Velvet");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gold");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reguler");

        jcbSweet.setBackground(new java.awt.Color(102, 102, 102));
        jcbSweet.setForeground(new java.awt.Color(204, 204, 204));
        jcbSweet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jcbVel.setBackground(new java.awt.Color(102, 102, 102));
        jcbVel.setForeground(new java.awt.Color(204, 204, 204));
        jcbVel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jcbGold.setBackground(new java.awt.Color(102, 102, 102));
        jcbGold.setForeground(new java.awt.Color(204, 204, 204));
        jcbGold.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jcbReg.setBackground(new java.awt.Color(102, 102, 102));
        jcbReg.setForeground(new java.awt.Color(204, 204, 204));
        jcbReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jcbDay.setBackground(new java.awt.Color(102, 102, 102));
        jcbDay.setForeground(new java.awt.Color(204, 204, 204));
        jcbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        jlblTktTp1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblTktTp1.setForeground(new java.awt.Color(153, 153, 153));
        jlblTktTp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTktTp1.setText("Film");
        jlblTktTp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jcbFilm.setBackground(new java.awt.Color(102, 102, 102));
        jcbFilm.setForeground(new java.awt.Color(204, 204, 204));
        jcbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deep", "Infinity War", "Alas Pati", "Kembang Kantil", "DeedPool2", "Jilangkung", "Rasuk" }));

        jlblTktTp2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblTktTp2.setForeground(new java.awt.Color(153, 153, 153));
        jlblTktTp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTktTp2.setText("Studio");
        jlblTktTp2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jcbStudio.setBackground(new java.awt.Color(102, 102, 102));
        jcbStudio.setForeground(new java.awt.Color(204, 204, 204));
        jcbStudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jbtnAdd.setBackground(new java.awt.Color(51, 51, 51));
        jbtnAdd.setForeground(new java.awt.Color(204, 204, 204));
        jbtnAdd.setText("Proses");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnRst.setBackground(new java.awt.Color(51, 51, 51));
        jbtnRst.setForeground(new java.awt.Color(204, 204, 204));
        jbtnRst.setText("Reset");
        jbtnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplTktTpLayout = new javax.swing.GroupLayout(jplTktTp);
        jplTktTp.setLayout(jplTktTpLayout);
        jplTktTpLayout.setHorizontalGroup(
            jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTktTpLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTpLayout.createSequentialGroup()
                        .addComponent(jcbStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jbtnRst)))
                    .addGroup(jplTktTpLayout.createSequentialGroup()
                        .addComponent(jlblTktTp1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTktTp))
                    .addGroup(jplTktTpLayout.createSequentialGroup()
                        .addComponent(jcbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jplTktTpLayout.createSequentialGroup()
                        .addComponent(jlblTktTp2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(20, 20, 20)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jplTktTpLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jbtnAdd))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTpLayout.createSequentialGroup()
                            .addComponent(jlblNoTkt)
                            .addGap(18, 18, 18)
                            .addComponent(jlblDay)
                            .addGap(12, 12, 12)))
                    .addGroup(jplTktTpLayout.createSequentialGroup()
                        .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbVel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbSweet, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbGold, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbReg, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jplTktTpLayout.setVerticalGroup(
            jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplTktTpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTktTp)
                    .addComponent(jlblNoTkt)
                    .addComponent(jlblDay)
                    .addComponent(jlblTktTp1))
                .addGap(18, 18, 18)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbSweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTktTp2))
                .addGap(18, 18, 18)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jplTktTpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdd)
                    .addComponent(jbtnRst))
                .addContainerGap())
        );

        jplTktTp1.setBackground(new java.awt.Color(51, 51, 51));
        jplTktTp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jplTktTp1.setForeground(new java.awt.Color(51, 51, 51));
        jplTktTp1.setPreferredSize(new java.awt.Dimension(134, 222));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Time");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Jumlah Tiket");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Nomer Pesanan");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Diskon");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Total");

        jlblDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblDate.setForeground(new java.awt.Color(153, 153, 153));
        jlblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblTime.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblTime.setForeground(new java.awt.Color(153, 153, 153));
        jlblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblNoT.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblNoT.setForeground(new java.awt.Color(153, 153, 153));
        jlblNoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNoT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblON.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblON.setForeground(new java.awt.Color(153, 153, 153));
        jlblON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblON.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblDis.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblDis.setForeground(new java.awt.Color(153, 153, 153));
        jlblDis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblTotal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jlblTotal.setForeground(new java.awt.Color(255, 0, 51));
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblOrdDet.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblOrdDet.setForeground(new java.awt.Color(153, 153, 153));
        jlblOrdDet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblOrdDet.setText("Order Details");
        jlblOrdDet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Film");

        jlblFilm.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblFilm.setForeground(new java.awt.Color(153, 153, 153));
        jlblFilm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblFilm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Studio");

        jlblStudio.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblStudio.setForeground(new java.awt.Color(153, 153, 153));
        jlblStudio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblStudio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jbtnExit.setBackground(new java.awt.Color(51, 51, 51));
        jbtnExit.setForeground(new java.awt.Color(204, 204, 204));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplTktTp1Layout = new javax.swing.GroupLayout(jplTktTp1);
        jplTktTp1.setLayout(jplTktTp1Layout);
        jplTktTp1Layout.setHorizontalGroup(
            jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jplTktTp1Layout.createSequentialGroup()
                            .addComponent(jlblDis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(117, 117, 117))
                        .addGroup(jplTktTp1Layout.createSequentialGroup()
                            .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnExit)
                            .addContainerGap()))
                    .addGroup(jplTktTp1Layout.createSequentialGroup()
                        .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblOrdDet, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblNoT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblON, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))))
        );
        jplTktTp1Layout.setVerticalGroup(
            jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOrdDet, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplTktTp1Layout.createSequentialGroup()
                        .addComponent(jlblON, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jlblFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTp1Layout.createSequentialGroup()
                                .addComponent(jbtnExit)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplTktTp1Layout.createSequentialGroup()
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jlblStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jlblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jlblNoT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jlblDis, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplTktTp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))))
                    .addComponent(jLabel8)))
        );

        jlblPrices.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblPrices.setForeground(new java.awt.Color(153, 153, 153));
        jlblPrices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPrices.setText("Harga ----------- Sweet Box Rp.100.000  -  Velvet Rp.75.000  -  Gold Rp.50.000  -  Reguler Rp.35.000");
        jlblPrices.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jlblPrices1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jlblPrices1.setForeground(new java.awt.Color(153, 153, 153));
        jlblPrices1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPrices1.setText("Spesial Diskon: Setiap Senin, diskon Rp.8000/tiket");
        jlblPrices1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblPrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPrices1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jplTktTp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jplTktTp1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPrices, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jlblPrices1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jplTktTp1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(jplTktTp, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
		this.getContentPane().setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_formWindowActivated

    private void jbtnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRstActionPerformed
        // TODO add your handling code here:
    jcbSweet.setSelectedIndex(0);
    jcbFilm.setSelectedIndex(0);
    jcbVel.setSelectedIndex(0);
    jcbGold.setSelectedIndex(0);
    jcbReg.setSelectedIndex(0);
    jcbDay.setSelectedIndex(0);
    jlblFilm.setText(null);
    jlblDate.setText(null);
    jlblTime.setText(null);
    jlblNoT.setText(null);
    jlblON.setText(null);
    jlblDis.setText(null);
    jlblTotal.setText(null);
    }//GEN-LAST:event_jbtnRstActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
		System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        
    //Random order number
    RandomOrder OrdNo = new RandomOrder();
    int Order = 0;
    jlblON.setText(String.valueOf(OrdNo.RandomOrdNum(Order)));
    //Check waktu
    Calendar timer = Calendar.getInstance();
    timer.getTime();
    SimpleDateFormat tTime = new SimpleDateFormat("HH:mm a");
    jlblTime.setText(tTime.format(timer.getTime()) );
    //Check Tanggal
    SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
    jlblDate.setText(tDate.format(timer.getTime())); 
    // Menampilkan film yang dipilih
     setFilm();                                     
     //Menampilkan Studio
    setStudio();
    //To get the total number of tickets
    jmlTkt();
   //Mensetting harga
    setHarga();
    //Total harga yang harus dibayar
    total();
    //Menampilkan diskon yang didapat
    diskon();                               

    }//GEN-LAST:event_jbtnAddActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
                //</editor-fold>
 //</editor-fold>           
//</editor-fold>

/* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new Main().setVisible(true);
                });
	}
public String setFilm() {
    this.Film = ((String)jcbFilm.getSelectedItem());
     jlblFilm.setText(String.valueOf(Film));
              return null;
}

private int Sweet = 0, Velvet = 0, Gold = 0, Reg = 0;
private String Day;
//Set Sweet Box tiket
public void setSweet(int Sweet) {
    this.Sweet = Integer.parseInt((String)jcbSweet.getSelectedItem());
}
//Get Sweet Box tiket
public int getSweet() {
    return Sweet;
}
//Set Velvet tiket
public void setVelvet(int Velvet) {
    this.Velvet = Integer.parseInt((String)jcbVel.getSelectedItem());
}
//Get Velvet  tiket
public int getVelvet() {
    return Velvet;
}
//Set Gold  tiket
public void setGold(int Gold){
    this.Gold = Integer.parseInt((String)jcbGold.getSelectedItem());
}
 //Get Gold tiket
public int getGold() {
     return Gold;
}
//Set Reguler tiket
public void setReg(int Reg) {
    this.Reg = Integer.parseInt((String)jcbReg.getSelectedItem());
}
//Get Regular tiket
public int getReg() {
     return Reg;
}
//Set Hari booking
public void setDay(String Day) {
    this.Day = ((String)jcbDay.getSelectedItem());
}
public String getSelectedDay() {
    return (String)jcbDay.getSelectedItem();
    }
public void jmlTkt() {
    int not =  (Integer.parseInt((String)jcbSweet.getSelectedItem())) + (Integer.parseInt((String)jcbVel.getSelectedItem())) + 
    (Integer.parseInt((String)jcbGold.getSelectedItem())) + (Integer.parseInt((String)jcbReg.getSelectedItem()));
    jlblNoT.setText(String.valueOf(not));
}
public void setStudio() {
    int not =  (Integer.parseInt((String)jcbStudio.getSelectedItem()));
    jlblStudio.setText(String.valueOf(not));
}
int sweet, velvet, gold, reg, total;
public void total () {
    total = (sweet * (Integer.parseInt((String)jcbSweet.getSelectedItem())) + (velvet * (Integer.parseInt((String)jcbVel.getSelectedItem()))) + 
    (gold * (Integer.parseInt((String)jcbGold.getSelectedItem()))) + (reg * (Integer.parseInt((String)jcbReg.getSelectedItem()))));
    jlblTotal.setText("Rp.  " + String.valueOf(total));
}
public void setHarga(){
    if (getSelectedDay().equals("Senin")) {
        sweet = 92000; velvet = 67000; gold = 42000; reg =32000;
}
    else {
        sweet = 100000; velvet = 75000; gold = 50000; reg = 40000;
}
}
public void diskon(){
    int diskon;
    if (getSelectedDay().equals("Senin")) {
        diskon =  ((Integer.parseInt((String)jcbSweet.getSelectedItem())) * 8000 ) + ((Integer.parseInt((String)jcbVel.getSelectedItem()))* 8000 ) + 
        ((Integer.parseInt((String)jcbGold.getSelectedItem())) * 8000 ) + ((Integer.parseInt((String)jcbReg.getSelectedItem())) * 8000 );
        jlblDis.setText("Rp.  " + String.valueOf(diskon));
}
    else {
        diskon = 0;
        jlblDis.setText("Rp.  " + String.valueOf(diskon));
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnRst;
    private javax.swing.JComboBox<String> jcbDay;
    private javax.swing.JComboBox<String> jcbFilm;
    private javax.swing.JComboBox<String> jcbGold;
    private javax.swing.JComboBox<String> jcbReg;
    private javax.swing.JComboBox<String> jcbStudio;
    public javax.swing.JComboBox<String> jcbSweet;
    private javax.swing.JComboBox<String> jcbVel;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblDay;
    private javax.swing.JLabel jlblDis;
    private javax.swing.JLabel jlblFilm;
    public javax.swing.JLabel jlblNoT;
    private javax.swing.JLabel jlblNoTkt;
    private javax.swing.JLabel jlblON;
    private javax.swing.JLabel jlblOrdDet;
    private javax.swing.JLabel jlblPrices;
    private javax.swing.JLabel jlblPrices1;
    private javax.swing.JLabel jlblStudio;
    private javax.swing.JLabel jlblTime;
    private javax.swing.JLabel jlblTktTp;
    private javax.swing.JLabel jlblTktTp1;
    private javax.swing.JLabel jlblTktTp2;
    private javax.swing.JLabel jlblTop;
    private javax.swing.JLabel jlblTop2;
    public javax.swing.JLabel jlblTotal;
    private javax.swing.JPanel jplTktTp;
    private javax.swing.JPanel jplTktTp1;
    // End of variables declaration//GEN-END:variables

 
}
